name: Build and deploy Node.js app to Azure Web App - course-calendar-staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm -v
          npm list vite
          npm run build --if-present
          echo "Root Directory after Build:"
          ls -R
          echo "Contents of 'dist' Directory:"
          if [ -d "dist" ]; then
            ls -R dist
          else
            echo "'dist' directory not found!"
            exit 1
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            dist/**/*  
            !node_modules/**
            !.git/**

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_02553D04CFF24FDB889A5DB08761859B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_048194D5069B4249828D4B7CC858A474 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_56A802B64D52461685CD0BDF215EADC8 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'course-calendar-staging'
          slot-name: 'Production'
          package: ./dist
